name: 'Get targets for Gluon release'
description: 'Returns targets available in a specified Gluon release'
inputs:
  gluon-version:
    description: 'Gluon commit hash to retrieve targets from'
    required: true
  broken:
    description: 'Determines if BROKEN targets should be returned (Default: 0)'
    default: 0
outputs:
  targets:
    description: 'JSON list containing all available Gluon-targets'
    value: ${{ steps.save-step.outputs.targets }}
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/entrypoint.sh /tmp/targets.json
      shell: bash
      env:
        GLUON_VERSION: ${{ inputs.gluon-version }}
        BROKEN: ${{ inputs.broken }}
    - run: cat /tmp/targets.json
      shell: bash
    - run: echo "targets=$(cat /tmp/targets.json)" >> "$GITHUB_OUTPUT"
      shell: bash
      id: save-step
