name: 'Get targets for Gluon release'
description: 'Returns targets available in a specified Gluon release'
inputs:
  gluon-path:
    description: 'Path to Gluon repository'
    required: true
  whitelist:
    description: 'Space-separated list of target whitelist'
    required: false
  broken:
    description: 'Determines if BROKEN targets should be returned (Default: 0)'
    default: 0
outputs:
  targets:
    description: 'JSON list containing all available Gluon-targets'
    value: ${{ steps.save-step.outputs.targets }}
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/entrypoint.sh $GITHUB_WORKSPACE/${{ inputs.gluon-path }} "${{ inputs.whitelist }}" > /tmp/targets.json
      shell: bash
      env:
        BROKEN: ${{ inputs.broken }}
    - run: echo "targets=$(cat /tmp/targets.json)" >> "$GITHUB_OUTPUT"
      shell: bash
      id: save-step
