name: "Create Artifact for single-target Gluon-build"
description: "Create an artifact for a single Gluon-target which can be re-used with the buildcombine actions"
inputs:
  gluon-path:
    description: 'Path to Gluon repository'
    required: true
  hardware-target:
    description: 'Target to build'
    required: true
runs:
  using: 'composite'
  steps:
    - run: mkdir -p "$GITHUB_WORKSPACE/build-artifact-workdir"
      shell: bash
    - run: tar -cJf "$GITHUB_WORKSPACE/build-artifact-workdir/output.tar.xz" -C ${{ inputs.gluon-path }} output
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.hardware-target }}
        path: build-artifact-workdir

