name: "Combine artifacts"
description: "Combine artifacts built by build-artifact"
inputs:
  workdir:
    description: 'Path in workspace to Workdir'
    required: true
  targets:
    description: 'JSON Array containing all names of targets build-jobs were created for'
    required: true
runs:
  using: 'composite'
  steps:
    - run: bash $GITHUB_ACTION_PATH/combine-build.sh
      shell: bash
      env:
        ACTION_ARTIFACT_DIR: ${{ inputs.workdir }}
        ACTION_TARGETS: ${{ inputs.targets }}
