name: "Build Gluon"
description: "Sign Gluon images using build-gluon container"
inputs:
  gluon-path:
    description: 'Path to a updated Gluon repository'
    required: true
  container-version:
    description: 'Container version to use'
    default: 'master'
  output-dir:
    description: 'Directory Gluons output folder is stored in'
    default: "gluon-output"
  signing-key:
    description: 'ECDSA key to sign manifest with'
    required: true
  manifest-branch:
    description: 'Manifest branch to sign'
    required: true

runs:
  using: 'composite'
  steps:
    - run: docker build --build-arg CONTAINER --build-arg VERSION -t sdk $GITHUB_ACTION_PATH
      env:
        VERSION: ${{ inputs.container-version }}
      shell: bash
    - run: mkdir -p ${RUNNER_TEMP}/gluon-signing-key; echo "${{ inputs.signing-key }}" > "${RUNNER_TEMP}/gluon-signing-key/signing.key"
      shell: bash
    - run: |
        docker run --rm \
          --user "$(id -u):$(id -g)" \
          --env ACTION_OUTPUT_DIR \
          --env ACTION_MANIFEST \
          --volume "${GITHUB_WORKSPACE}/${ACTION_OUTPUT_DIR}:/gluon/output-dir" \
          --volume "${GITHUB_WORKSPACE}:/gluon/site-repo" \
          --volume "${GITHUB_WORKSPACE}/${ACTION_GLUON_PATH}:/gluon/gluon-repo" \
          --volume "${RUNNER_TEMP}/gluon-signing-key:/gluon/signing-key" \
          sdk
      env:
        ACTION_GLUON_PATH: ${{ inputs.gluon-path }}
        ACTION_OUTPUT_DIR: ${{ inputs.output-dir }}
        ACTION_MANIFEST: ${{ inputs.manifest-branch }}
      shell: bash
