name: "Build OpenWrt host-tools"
description: "Build reusable OpenWrt host-tools for use with Gluon"
inputs:
  gluon-version:
    description: 'Gluon commit hash to build'
    required: true
  container-version:
    description: 'Container version to use'
    default: 'master'
  use-cache:
    description: 'Restore and save generated host-tools to GitHub actions cache'
    default: true
  store-artifacts:
    description: 'Store resulting host-tools as artifact to use for consecutive steps'
    default: true

runs:
  using: 'composite'
  steps:
    - run: git clone https://github.com/freifunk-gluon/gluon.git ${RUNNER_TEMP}/gluon; cd ${RUNNER_TEMP}/gluon; git checkout ${{ inputs.gluon-version }}
      if: steps.cache-tools.outputs.cache-hit != 'true'
      shell: bash
    - name: Determine Cache-Key
      id: cache-key
      run: echo "cache-key=$(bash $GITHUB_ACTION_PATH/cache-key.sh ${RUNNER_TEMP}/gluon)" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Print Cache-Key
      run: echo ${{ steps.cache-key.outputs.cache-key }}
      shell: bash
    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v3
      with:
        path: cache/tools
        key: ${{ steps.cache-key.outputs.cache-key }}-tools
    - run: docker build --build-arg CONTAINER --build-arg VERSION -t sdk $GITHUB_ACTION_PATH
      if: steps.cache-tools.outputs.cache-hit != 'true'
      env:
        VERSION: ${{ inputs.container-version }}
      shell: bash
    - run: mkdir -p "${GITHUB_WORKSPACE}/cache/tools"
      if: steps.cache-tools.outputs.cache-hit != 'true'
      shell: bash
    - run: tree "${GITHUB_WORKSPACE}"
      shell: bash
    - run: |
        docker run --rm \
          --user "$(id -u):$(id -g)" \
          --env VERSION \
          --volume "${GITHUB_WORKSPACE}:/gluon/site-repo" \
          --volume "${GITHUB_WORKSPACE}/cache/tools:/gluon/artifacts" \
          --volume "${RUNNER_TEMP}/gluon:/gluon/gluon-repo" \
          sdk
      if: steps.cache-tools.outputs.cache-hit != 'true'
      env:
        VERSION: ${{ inputs.gluon-version }}
      shell: bash
    - name: Archive output
      uses: actions/upload-artifact@v3
      with:
        name: host-tools
        path: cache/tools

