name: "Build Gluon images"
on: [push]

jobs:
  build-meta:
    outputs:
      release-version: ${{ steps.build-metadata.outputs.release-version }}
      autoupdater-enabled: ${{ steps.build-metadata.outputs.autoupdater-enabled }}
      autoupdater-branch: ${{ steps.build-metadata.outputs.autoupdater-branch }}
      manifest-branches: ${{ steps.build-metadata.outputs.manifest-branches }}
    runs-on: ubuntu-latest
    name: Determine build-meta
    steps:
      - uses: actions/checkout@v3
      - name: Get build-metadata
        id: build-metadata
        run: bash .github/build-meta.sh
      - name: Print build-metadata
        run: cat $GITHUB_OUTPUT

  targets:
    needs: build-meta
    outputs:
      targets: ${{ steps.get-targets.outputs.targets }}
    runs-on: ubuntu-latest
    name: Get Gluon targets
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'freifunk-gluon/gluon'
          ref: 'master'
          path: 'gluon-gha-data/gluon'
      - name: Get Targets
        uses: ./.github/actions/get-targets
        id: get-targets
        with:
          gluon-path: "gluon-gha-data/gluon"
          broken: "1"

  host-tools:
    needs: build-meta
    runs-on: ubuntu-latest
    name: Build host-tools
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'blocktrron/gluon'
          ref: 'fix-host-double-build'
          path: 'gluon-gha-data/gluon'
      - name: Build host-tools
        uses: ./.github/actions/tools
        id: build-host-tools
        with:
          gluon-path: "gluon-gha-data/gluon"
          output-path: "gluon-gha-data/openwrt"
      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: openwrt
          path: "gluon-gha-data/openwrt"

  build:
    needs: [ targets, build-meta, host-tools ]
    if: ${{ needs.targets.outputs.targets != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.targets.outputs.targets) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'blocktrron/gluon'
          ref: 'fix-host-double-build'
          path: 'gluon-gha-data/gluon'

      - name: Download prepared OpenWrt
        uses: actions/download-artifact@v3
        with:
          name: openwrt
          path: "gluon-gha-data/openwrt"

      - name: Gluon Update
        uses: ./.github/actions/build
        id: update-gluon
        with: 
          gluon-path: "gluon-gha-data/gluon"
          hardware-target: ath79-generic
          make-target: update

      - name: Restore host-tools
        run: tar xf gluon-gha-data/openwrt/openwrt.tar.xz -C gluon-gha-data/gluon/openwrt
      
      - name: Print directory structure
        run: tree gluon-gha-data/gluon/openwrt

      - name: Build
        uses: ./.github/actions/build
        id: build-gluon
        with:
          gluon-path: "gluon-gha-data/gluon"
          hardware-target: ${{ matrix.target }}
          broken: "1"
          deprecated: "0"
          autoupdater-enabled: ${{ needs.build-meta.outputs.autoupdater-enabled }}
          autoupdater-branch: ${{ needs.build-meta.outputs.autoupdater-branch }}
          release: ${{ needs.build-meta.outputs.release-version }}
      
      - name: Pack and Upload build output
        uses: ./.github/actions/build-artifact
        with:
          gluon-path: "gluon-gha-data/gluon"
          hardware-target: ${{ matrix.target }}

  manifest:
    needs: [ build, build-meta, targets ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Combine Build output
        uses: ./.github/actions/build-artifact
        with:
          workdir: "gluon-gha-data/gluon"
      - name: Archive output
        uses: actions/upload-artifact@v3
        with:
          name: combined-manifest
          path: gluon-gha-data/gluon

  sign:
    needs: [ manifest, build-meta ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: combined-manifest
          path: artifact-in
      - name: Sign manifest
        uses: ./.github/actions/sign
        id: sign
        with:
          gluon-version: "master"
          output-dir: artifact-in
          signing-key: 50b2b068ed87c0c3456e337292af8f9dd05343501894c9501025bb7f1a625d60
          manifest-branches: "${{ needs.build-meta.outputs.autoupdater-branch }}" 
      - name: Archive output
        uses: actions/upload-artifact@v3
        with:
          name: combined-signed
          path: artifact-in